import React, { useState } from 'react';
import { FileText, Download, Check, Loader2, Presentation, File, X } from 'lucide-react';
import pptxgen from 'pptxgenjs';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType } from 'docx';
import { saveAs } from 'file-saver';

interface DocumentGeneratorProps {
  type: 'ppt' | 'pdf' | 'word';
  title: string;
  content: any; // Structured content for the document
  onComplete?: () => void;
}

export const DocumentGenerator: React.FC<DocumentGeneratorProps> = ({ type, title, content, onComplete }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Helper to extract values from multiple possible keys
  const getVal = (item: any, keys: string[]) => {
    if (!item || typeof item !== 'object') return null;
    for (const key of keys) {
      if (item[key]) return item[key];
    }
    return null;
  };

  const sanitizeFilename = (name: string) => {
    return (name || 'document').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  };

  const generatePPT = async () => {
    try {
      const pres = new pptxgen();
      pres.layout = 'LAYOUT_16x9';

      // Title Slide - Modern Dark Theme
      const titleSlide = pres.addSlide();
      titleSlide.background = { color: '1A1A1A' };
      
      titleSlide.addText(title || 'Untitled Document', { 
        x: 1, y: 1.5, w: '80%', h: 1.5, 
        fontSize: 44, bold: true, align: 'center', 
        color: '0AFFFF', fontFace: 'Arial' 
      });
      
      titleSlide.addShape(pres.ShapeType.rect, { 
        x: 3, y: 3.2, w: 4, h: 0.05, fill: { color: '0AFFFF' } 
      });

      titleSlide.addText('Generated by Nexus AI', { 
        x: 1, y: 3.5, w: '80%', h: 0.5, 
        fontSize: 18, align: 'center', 
        color: 'FFFFFF', italic: true 
      });

      // Content Slides
      const contentArray = Array.isArray(content) ? content : (content ? [content] : []);
      
      contentArray.forEach((item: any, idx: number) => {
        const slide = pres.addSlide();
        slide.background = { color: idx % 2 === 0 ? 'F8F9FA' : 'FFFFFF' };
        
        const heading = getVal(item, ['heading', 'title', 'header', 'slideTitle']) || `Section ${idx + 1}`;
        const bodyText = getVal(item, ['text', 'body', 'content', 'description']);
        const bullets = getVal(item, ['bullets', 'points', 'list']);

        // Header Bar
        slide.addShape(pres.ShapeType.rect, { 
          x: 0, y: 0, w: '100%', h: 0.8, fill: { color: '1A1A1A' } 
        });
        
        slide.addText(heading, { 
          x: 0.5, y: 0.15, w: '90%', h: 0.5, 
          fontSize: 28, bold: true, color: '0AFFFF' 
        });
        
        if (bullets && Array.isArray(bullets)) {
          slide.addText(bullets.map((b: string) => `• ${b}`).join('\n'), {
            x: 0.5, y: 1.2, w: '90%', h: 3.5, 
            fontSize: 18, color: '333333', 
            lineSpacing: 28,
            bullet: { type: 'bullet', code: '2022' }
          });
        } else if (bodyText) {
          slide.addText(String(bodyText), { 
            x: 0.5, y: 1.2, w: '90%', h: 3.5, 
            fontSize: 18, color: '333333',
            align: 'left',
            valign: 'top'
          });
        }
      });

      await pres.writeFile({ fileName: `${sanitizeFilename(title)}.pptx` });
    } catch (err) {
      console.error('PPT generation error:', err);
      throw new Error('Failed to generate PowerPoint');
    }
  };

  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      
      // Helper for Header
      const addHeader = (d: any) => {
        d.setFillColor(10, 255, 255);
        d.rect(margin, 15, 2, 10, 'F');
        d.setFont('helvetica', 'bold');
        d.setFontSize(10);
        d.setTextColor(100, 100, 100);
        d.text('NEXUS AI DOCUMENT', margin + 5, 22);
        d.setDrawColor(230, 230, 230);
        d.line(margin, 28, pageWidth - margin, 28);
      };

      // Helper for Footer
      const addFooter = (d: any, pageNum: number) => {
        d.setFont('helvetica', 'normal');
        d.setFontSize(8);
        d.setTextColor(150, 150, 150);
        d.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        d.text(new Date().toLocaleDateString(), margin, pageHeight - 10);
      };

      // Title Page
      addHeader(doc);
      doc.setFontSize(28);
      doc.setTextColor(26, 26, 26);
      const safeTitle = title || 'Untitled Document';
      const titleLines = doc.splitTextToSize(safeTitle, contentWidth);
      doc.text(titleLines, margin, 50);
      
      doc.setFontSize(12);
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, margin, 50 + (titleLines.length * 10) + 5);
      
      let y = 50 + (titleLines.length * 10) + 25;
      let currentPage = 1;
      addFooter(doc, currentPage);

      const contentArray = Array.isArray(content) ? content : (content ? [content] : []);

      contentArray.forEach((item: any, idx: number) => {
        const heading = getVal(item, ['heading', 'title', 'header', 'slideTitle']) || `Section ${idx + 1}`;
        const bodyText = getVal(item, ['text', 'body', 'content', 'description']);
        const bullets = getVal(item, ['bullets', 'points', 'list']);

        // Check for page break before heading
        if (y > pageHeight - 40) {
          doc.addPage();
          currentPage++;
          addHeader(doc);
          addFooter(doc, currentPage);
          y = 40;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(26, 26, 26);
        doc.text(String(heading), margin, y);
        y += 8;
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        
        if (bullets && Array.isArray(bullets)) {
          bullets.forEach((bullet: string) => {
            const splitBullet = doc.splitTextToSize(`• ${bullet}`, contentWidth - 5);
            if (y + (splitBullet.length * 6) > pageHeight - 20) {
              doc.addPage();
              currentPage++;
              addHeader(doc);
              addFooter(doc, currentPage);
              y = 40;
            }
            doc.text(splitBullet, margin + 5, y);
            y += (splitBullet.length * 6) + 2;
          });
          y += 4;
        } else if (bodyText) {
          const splitText = doc.splitTextToSize(String(bodyText), contentWidth);
          if (y + (splitText.length * 6) > pageHeight - 20) {
            doc.addPage();
            currentPage++;
            addHeader(doc);
            addFooter(doc, currentPage);
            y = 40;
          }
          doc.text(splitText, margin, y);
          y += (splitText.length * 6) + 8;
        }
      });

      doc.save(`${sanitizeFilename(title)}.pdf`);
    } catch (err) {
      console.error('PDF generation error:', err);
      throw new Error('Failed to generate PDF');
    }
  };

  const generateWord = async () => {
    try {
      const children = [
        new Paragraph({
          children: [new TextRun({ text: title || 'Untitled Document', bold: true, size: 48, color: '1A1A1A' })],
          spacing: { after: 400 }
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Generated by Nexus AI', italics: true, size: 20, color: '666666' })],
          spacing: { after: 800 }
        })
      ];
      
      const contentArray = Array.isArray(content) ? content : (content ? [content] : []);

      contentArray.forEach((item: any, idx: number) => {
        const heading = getVal(item, ['heading', 'title', 'header', 'slideTitle']) || `Section ${idx + 1}`;
        const bodyText = getVal(item, ['text', 'body', 'content', 'description']);
        const bullets = getVal(item, ['bullets', 'points', 'list']);

        children.push(
          new Paragraph({
            children: [new TextRun({ text: String(heading), bold: true, size: 32, color: '0AFFFF' })],
            spacing: { before: 400, after: 200 }
          })
        );

        if (bullets && Array.isArray(bullets)) {
          bullets.forEach((bullet: string) => {
            children.push(
              new Paragraph({
                children: [new TextRun({ text: String(bullet), size: 24 })],
                bullet: { level: 0 }
              })
            );
          });
        } else if (bodyText) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: String(bodyText), size: 24 })]
            })
          );
        }
      });

      const doc = new Document({
        sections: [{
          children: children
        }]
      });
      
      const blob = await Packer.toBlob(doc);
      saveAs(blob, `${sanitizeFilename(title)}.docx`);
    } catch (err) {
      console.error('Word generation error:', err);
      throw new Error('Failed to generate Word document');
    }
  };

  const handleDownload = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      if (type === 'ppt') await generatePPT();
      else if (type === 'pdf') await generatePDF();
      else if (type === 'word') await generateWord();
      
      setIsDownloaded(true);
      if (onComplete) onComplete();
    } catch (err: any) {
      console.error('Generation failed:', err);
      setError(err.message || 'Generation failed');
    } finally {
      setIsGenerating(false);
    }
  };


  const getIcon = () => {
    switch (type) {
      case 'ppt': return <Presentation className="w-4 h-4" />;
      case 'pdf': return <FileText className="w-4 h-4" />;
      case 'word': return <File className="w-4 h-4" />;
    }
  };

  const getColorClass = () => {
    switch (type) {
      case 'ppt': return 'bg-orange-500/10 text-orange-400 border-orange-500/20';
      case 'pdf': return 'bg-red-500/10 text-red-400 border-red-500/20';
      case 'word': return 'bg-blue-500/10 text-blue-400 border-blue-500/20';
    }
  };

  return (
    <div className={`mt-3 p-3 rounded-xl border backdrop-blur-md transition-all ${getColorClass()}`}>
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-3 min-w-0">
          <div className="p-2 bg-black/20 rounded-lg flex-shrink-0">
            {getIcon()}
          </div>
          <div className="min-w-0">
            <h3 className="font-bold text-sm truncate">{title}</h3>
            <p className="text-[10px] opacity-60 uppercase tracking-wider font-bold truncate">
              {type === 'ppt' ? 'PowerPoint' : type === 'pdf' ? 'PDF' : 'Word'}
            </p>
          </div>
        </div>
        
        <button
          onClick={handleDownload}
          disabled={isGenerating}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all active:scale-95 flex-shrink-0 ${
            isDownloaded 
              ? 'bg-emerald-500 text-white' 
              : error
              ? 'bg-red-500 text-white'
              : 'bg-white/10 hover:bg-white/20 text-white border border-white/10'
          }`}
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-3 h-3 animate-spin" />
              <span>...</span>
            </>
          ) : isDownloaded ? (
            <>
              <Check className="w-3 h-3" />
              <span>Saved</span>
            </>
          ) : error ? (
            <>
              <X className="w-3 h-3" />
              <span>Retry</span>
            </>
          ) : (
            <>
              <Download className="w-3 h-3" />
              <span>Get {type.toUpperCase()}</span>
            </>
          )}
        </button>
      </div>
      {error && (
        <p className="mt-2 text-[10px] text-red-400 font-medium bg-red-500/10 p-1.5 rounded-lg border border-red-500/20">
          {error}
        </p>
      )}
    </div>
  );
};
